### ISSUE TITLE
Always drive backwards

### ISSUE THREAD

**Issue by porglezomp** [FRC1076/FRC1076-2016-Competition#42] opened 2016-06-16 22:34 UTC
Auto states should unconditionally be backwards

**Comment by vivianbp** [comment] 2016-06-17 16:29
thats a feature, not a bug ;)

On Thu, Jun 16, 2016 at 6:34 PM Caleb Jones notifications@github.com
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/FRC1076/FRC1076-2016-Competition/issues/42, or mute
> the thread
> https://github.com/notifications/unsubscribe/AGKVe-eLDhBBfsNrxP6l31RMKRlTHIKgks5qMc-CgaJpZM4I34FI
> .
> 
> ## 
> 
> Thank you,
>      Victor Boyse-Peacor

Student of Engineering at University of Michigan
Tech Consultant at Department Computing Organization at EECS
Doing Research at RAM-lab through UROP

**Comment by a2aaron** [comment] 2016-06-22 21:02
From Solomon's email
- I would like the robot to ALWAYS drive over the defensive obstacle backwards. This guarantees that we will never drive the wrong way if something happens with the driver station (especially with rookie drivers controlling the robot at these two events).

**Comment by a2aaron** [comment] 2016-06-23 23:01
Caleb, Can I take this issue even though you assigned it to yourself?

**Comment by a2aaron** [comment] 2016-06-23 23:04
What do the two different autonomous routines in Robot.java do? There's one built using constructor chains and another built using the mini-compiler.

**Comment by a2aaron** [comment] 2016-06-23 23:24
OK, looking the autonomous constructed from state chains, it appears to always drive backwards. In addition, it also looks like it attacks the right side of the tower.

The one that uses the mini-compiler does not activate but I can't understand how it does anything useful. Presumably, it drives forward, takes a ball from the center, rotate, drives using vision and then tries to shoot twice. I'm not sure if that was ever tested or even used.

**Comment by porglezomp** [comment] 2016-06-24 03:10
I think the mini-compiled one was the one that almost scored during the last few rounds of the event last time.

**Comment by a2aaron** [comment] 2016-06-26 01:24
#57 technically fixes this but it's ugly.

**Comment by a2aaron** [comment] 2016-07-09 12:34
Closing as fixed by #57.

**Closed as completed by a2aaron** 2016-07-09 12:34 UTC
